[package]
name = "native"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
url = "2.5.4"
thiserror = "2.0.12"
serde_json = "1.0.142"
dirs = "6.0.0"
chrono = { version =  "0.4.41", features = ["serde"] }
tempfile = "3.20.0"
ctrlc = "3.4.7"
